trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
    - azure-pipeline-3E.yml
    - .env-example
    - env-example

pr: none

pool:  linux

steps:

- task: DownloadSecureFile@1
  name: env
  inputs:
    secureFile: 'dac6-env'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        myPwd=$(pwd)
        if [ ! -d $(DIR) ]; then mkdir $(DIR); fi
        cp -r $myPwd/* $(DIR)
        cd $(DIR)
        cp $(env.secureFilePath) $(DIR)/.env
        npm install
        chown -R node:node $(DIR)
